apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: deployment-svc-ex
spec: 
  selector: 
    matchLabels:
      app: test-svc
  replicas: 3
  template: 
    metadata: 
      labels: 
        app: test-svc 
    spec: 
      containers: 
        - image: nginx:1.25.1-perl
          name: nginx
          ports: 
            - containerPort: 80 