apiVersion: v1 
kind: Service 
metadata: 
  name: svc-loadbalancer
spec: 
  selector: 
    app: test-svc 
  ports: 
    - protocol: TCP 
      port: 80
      targetPort: 80
  type: LoadBalancer